version: "3.8"

services:

  client:
    build:
      context: ./client
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka1
      - kafka2
      - kafka3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DLL_AUTO=update
      - KAFKA_BOOTSTRAP_SERVERS=TCP://kafka1:9091, TCP://kafka2:9092, TCP://kafka3:9093
      - SERVER_PORT=8081
      - THREAD_POOL_CORE_POOL_SIZE=50
      - THREAD_POOL_MAX_POOL_SIZE=100
      - THREAD_POOL_QUEUE_CAPACITY=200
      - KAFKA_TOPIC_PARTITIONS=10
      - KAFKA_TOPIC_REPLICATION=1
      - KAFKA_LISTENER_CONTAINER_CONCURRENCY=10

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=TCP://kafka1:9091, TCP://kafka2:9092, TCP://kafka3:9093
      - SERVER_PORT=8080
      - KAFKA_TOPIC_PARTITIONS=10
      - KAFKA_TOPIC_REPLICATION=1

  postgres:
    image: postgres:16-alpine3.19
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    restart: on-failure
    volumes:
      - zookeeper:/var/lib/zookeeper/
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    restart: on-failure
    volumes:
      - kafka1:/var/lib/kafka/
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: on-failure
    volumes:
      - kafka2:/var/lib/kafka/
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    restart: on-failure
    volumes:
      - kafka3:/var/lib/kafka/
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

volumes:
  kafka1:
  kafka2:
  kafka3:
  zookeeper:
  postgres:
